# Generated by Django 4.2.4 on 2023-08-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0005_alter_action_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='category_1',
            field=models.CharField(default='action', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='category_2',
            field=models.CharField(default='action', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='category_3',
            field=models.CharField(default='action', max_length=100),
        ),
    ]
